# Generated by Django 6.0.4 on 2026-04-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.barang')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toko.transaksi')),
            ],
        ),
    ]
