# Generated by Django 6.0.4 on 2026-04-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailTransaksi',
        ),
    ]
