# Generated by Django 6.0.4 on 2026-04-17 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0003_detailtransaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='detailtransaksi',
            name='transaksi',
        ),
        migrations.DeleteModel(
            name='Barang',
        ),
        migrations.DeleteModel(
            name='DetailTransaksi',
        ),
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
